// Copyright (c) 2017, 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-opentracing
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-guide-category: microprofile
:page-essential: false
:page-releasedate: 2018-03-16
:page-description: Explore how to enable and customize tracing of JAX-RS and non-JAX-RS methods by using MicroProfile OpenTracing.
:page-tags: ['MicroProfile', 'OpenTracing', 'microservices', '@Traced']
:page-permalink: /guides/{projectid}
:page-related-guides: ['cdi-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:page-seo-title: Enabling distributed tracing in Java microservices using Eclipse MicroProfile OpenTracing
:page-seo-description: A getting started tutorial and an example on how to enable distributed tracing in Java microservices to easily trace request flows that span multiple resources by using MicroProfile OpenTracing and Jaeger tracing system.
:source-highlighter: prettify
:guide-author: Open Liberty
= Enabling distributed tracing in microservices

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to enable and customize tracing of JAX-RS and non-JAX-RS methods by using MicroProfile OpenTracing.


:inv-url: http://localhost:9081/inventory/systems
:inv-url-docker: http://localhost:9080/inventory/systems
:sys-url: http://localhost:9080/system/properties
:jaeger-url: http://localhost:16686


== What you'll learn

You will learn how to enable automatic tracing for JAX-RS methods as well as create custom tracers
for non-JAX-RS methods by using MicroProfile OpenTracing.

OpenTracing is a standard API for instrumenting microservices for distributed tracing. Distributed
tracing helps troubleshoot microservices by examining and logging requests as they propagate through a
distributed system, allowing developers to tackle the otherwise difficult task of debugging these requests.
Without a distributed tracing system in place, analyzing the workflows of operations becomes difficult,
particularly in regard to pinpointing when and by whom a request is received, as well as when a response
is sent back.

MicroProfile OpenTracing enables distributed tracing in microservices without adding any explicit
distributed tracing code to the application. Note that the MicroProfile OpenTracing specification does
not address the problem of defining, implementing, or configuring the underlying distributed tracing
system. Rather, the specification makes it easy to instrument services with distributed tracing given
an existing distributed tracing system.

https://www.jaegertracing.io/[Jaeger^] is a an open-sourced distributed tracing system which is compatible with the
OpenTracing specification. Jaeger also provides an implementation of `Tracer` in their client package that is compatible
with MicroProfile OpenTracing.

You will configure the provided `inventory` and `system` services to use Jaeger for distributed tracing with
MicroProfile OpenTracing. You will run these services in two separate JVMs made of two server instances
to demonstrate tracing in a distributed environment. If all the components were to run on a single
server, then any logging software would do the trick.

== Additional prerequisites
You will use Docker in this guide to deploy the Jaeger server. For Docker installation instructions, refer to the
official https://docs.docker.com/install/[Docker documentation^].

=== Deploying Jaeger
You can start the Jaeger all-in-one executable using Docker
[role='command']
```
docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 14250:14250 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.17
```

You can find more information about the Jaeger server in their
https://www.jaegertracing.io/docs/1.17/getting-started/[Getting Started^] documentation.

Before you proceed, make sure that your Jaeger server is up and running. Jaeger can be found
at the {jaeger-url}[{jaeger-url}^] URL.

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished application. Give it a try before you proceed.


Open a command-line session and navigate to the `finish/inventory` directory.
Run the following Maven goal to build the service and deploy it to Open Liberty:
[role="command"]
----
mvn liberty:run
----

Open another command-line session and navigate to the `finish/system` directory.
Run the following Maven goal to build the services and deploy them to Open Liberty:
[role="command"]
----
mvn liberty:run
----


After you see the following message, your application server is ready.

[role="no_copy"]
----
The defaultServer server is ready to run a smarter planet.
----

Make sure that your Jaeger server is running and point your browser to the {inv-url}/localhost[{inv-url}/localhost^] URL.
When you visit this endpoint, you make two GET HTTP requests, one to the `system` service and one to the `inventory`
service. Both of these requests are configured to be traced, so a new trace will be recorded in Jaeger.

To view the traces, visit the {jaeger-url}[{jaeger-url}^] URL. Under the `Search` tab in the top-left,
you can view the traces for the `inventory` or `system` services by selecting them in the
`Select a service` dropdown and clicking the `Find Traces` button at the bottom of the section.

If you only see the `jaeger-query` listed in the dropdown, you may need to wait a little longer and refresh the page
to see the application services.

View the traces for `inventory`. You should see a trace with the following header:
[role='no_copy']
----
inventory: GET:io.openliberty.guides.inventory.InventoryResource.getPropertiesForHost
----

The trace should have 4 spans, 3 from `inventory` and 1 from `system`. Click on the trace to view its details.
Under `Service & Operation`, you should see the spans in this trace.
You can inspect each span by clicking it to reveal more detailed information, such as the time
at which the request was received and the time at which a response was sent back.

Verify that there are three spans from `inventory`:

- `GET:io.openliberty.guides.inventory.InventoryResource.getPropertiesForHost` (JAX-RS)
- `GET` (JAX-RS Client)
- `add() Span` (Custom Tracer injection)

Verify that there is one span from `system`:

- `GET:io.openliberty.guides.system.SystemResource.getProperties` (JAX-RS)

After you are finished checking out the application, stop the Open Liberty servers by pressing CTRL+C in the
shell sessions where you ran the `system` and `inventory` services.
Alternatively, you can run the `liberty:stop` goal from the finish directory in another shell session for the `inventory`
and `system` modules:
[role="command"]
----
mvn -pl system,inventory liberty:stop
----

// =================================================================================================
// Running the services
// =================================================================================================
== Building the application

You'll need to start the services to see basic traces appear in Jaeger. You will need two command-line instances to
start the two services in development mode.
Open a command-line session and navigate to the `start/inventory` directory.
Open another command-line session and navigate to the `start/system` directory.

[role='command']
include::{common-includes}/devmode-start.adoc[]

When the servers start, you can find the `system` and `inventory` services at the following URLs:

- {sys-url}[{sys-url}^]
- {inv-url}[{inv-url}^]

// =================================================================================================
// Existing Tracer implementation
// =================================================================================================

== Existing Tracer implementation

To collect traces across your systems, you need to implement the OpenTracing `Tracer`
interface.
Jaeger provides a `Tracer` implementation for the Jaeger server in the `jaeger-client` package.

This package is already added as a dependency for you in your [hotspot=jaeger]`pom.xml` file.
It will be downloaded and installed automatically into each service when you run a Maven build.

pom.xml
[source, xml, linenums, role='code_column']
----
include::finish/inventory/pom.xml[]
----

// =================================================================================================
// Enabling distributed tracing
// =================================================================================================

== Enabling distributed tracing

The MicroProfile OpenTracing feature enables tracing of all JAX-RS methods by default.
To further control and customize these traces, use the `@Traced` annotation to enable and disable
tracing of particular methods. You can also inject a custom `Tracer` object to create and customize spans.

This feature is already enabled in the `inventory` and `system` configuration files.

=== Enabling distributed tracing without code instrumentation

Because tracing of all JAX-RS methods is enabled by default, you need only to enable
[hotspot=mpOpenTracing file=0]`MicroProfile OpenTracing` feature in the `server.xml` file
to see some basic traces in Jaeger.

To add the availability of Jaeger APIs to the application, `third-party` must be added to the types of API packages that
this class loader.
Instead of explicitly configuring a list of API packages which includes `third-party`, the value `+third-party` can be
set to the [hotspot=thirdParty]`apiTypeVisibility` attribute of the [hotspot=thirdParty]`<classLoader />`
configuration to add `third-party` to the default list of API package types supported.

server.xml
[source, xml, linenums, role='code_column']
----
include::finish/inventory/src/main/liberty/config/server.xml[]
----

Make sure that your services are running. Then, simply point your browser to any of their endpoints and
check your Jaeger server for traces.

=== Enabling explicit distributed tracing

Use the [hotspot=Traced file=0]`@Traced` annotation to define explicit span creation for specific classes and methods.
If you place the annotation on a class, then it's automatically applied to all methods within that class.
If you place the annotation on a method, then it overrides the class annotation if one exists.

The [hotspot=Traced file=0]`@Traced` annotation can be configured with the following two parameters:

- The `value=[true|false]` parameter indicates whether or not a particular class or method is
traced. For example, while all JAX-RS methods are traced by default, you can disable their tracing by
using the `@Traced(false)` annotation. This parameter is set to `true` by default.
- The `operationName=<Span name>` parameter indicates the name of the span that is assigned to the
particular method that is traced. If you omit this parameter, the span will be named with the following
form: `<package name>.<class name>.<method name>`. If you use this parameter at a class level, then
all methods within that class will have the same span name unless they are explicitly overridden by
another `@Traced` annotation.

[role="code_command hotspot file=0", subs="quotes"]
----
#Update the `InventoryManager` class.#
`inventory/src/main/java/io/openliberty/guides/inventory/InventoryManager.java`
----
[role="edit_command_text"]
Enable tracing of the [hotspot=list file=0]`list()` non-JAX-RS method by updating [hotspot=Traced file=0]`@Traced` as shown.

InventoryManager.java
[source, Java, linenums, role='code_column tags=addToInvList hide_tags=copyright,customTracer,Try']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[]
----

Point to the {inv-url}[{inv-url}^] URL and check your Jaeger server at {jaeger-url}[{jaeger-url}^].
Select the `inventory` traces and click the `Find Traces` button.

You see a new trace record that is two spans long with one span for the [hotspot=listContents file=1]`listContents()`
JAX-RS method in the [hotspot file=1]`InventoryResource` class and another span for the [hotspot=list file=0]`list()`
method in the [hotspot file=0]`InventoryManager` class.

Verify that these spans have the following names:

- `GET:io.openliberty.guides.inventory.InventoryResource.listContents`
- `InventoryManager.list`

[role="code_command hotspot file=1", subs="quotes"]
----
#Update the `InventoryResource` class#
`inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java`
----
[role="edit_command_text"]
Disable tracing of the [hotspot=listContents file=1]`listContents()` JAX-RS method by setting [hotspot=Traced-false file=1]`@Traced(false)`.

InventoryResource.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[]
----

Point to the {inv-url}[{inv-url}^] URL and check your Jaeger server at {jaeger-url}[{jaeger-url}^].
Select the `inventory` traces and click the `Find Traces` button.
You see a new trace record that is just one span long for the remaining [hotspot=list file=0]`list()` method in the
`InventoryManager` class.
Verify that this span has the following name:

- `InventoryManager.list`

=== Injecting a custom Tracer object

The MicroProfile OpenTracing specification also makes the underlying OpenTracing `Tracer` instance
available for use. You can access the configured `Tracer` by injecting it into a bean by using the [hotspot=customTracer file=0]`@Inject`
annotation from the Contexts and Dependency Injections API.

Inject the `Tracer` object into the `inventory/src/main/java/io/openliberty/guides/inventory/InventoryManager.java` file.
Then, use it to define a new child scope in the [hotspot=addSpan file=0]`add()` call.

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `InventoryManager` class.#
`inventory/src/main/java/io/openliberty/guides/inventory/InventoryManager.java`
----

InventoryManager.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[]
----

The [hotspot=Try file=0]`try` block that you see here is called a `try-with-resources` statement, meaning that the
`childScope` object is closed at the end of the statement.
It's good practice to define custom spans inside such statements.
Otherwise, any exceptions that are thrown before the span is closed will leak the active span.

Point to the {inv-url}/localhost[{inv-url}/localhost^] URL and check your Jaeger server at {jaeger-url}[{jaeger-url}^].
Select the `inventory` traces and click the `Find Traces` button.
Verify that the spans in the new trace have the following names:

The `system` trace:

- `GET:io.openliberty.guides.system.SystemResource.getProperties`

The `inventory` trace:

- `GET:io.openliberty.guides.inventory.InventoryResource.getPropertiesForHost`
- `GET`
- `add() Span`

This simple example shows what you can do with the injected `Tracer` object. More configuration
options are available to you, including setting a timestamp for when a span was created and destroyed.
However, these options require an implementation of their own, which does not come as a part of the Jaeger
user feature that is provided. In a real-world scenario, implement all the OpenTracing interfaces that
you deem necessary, which might include the `SpanBuilder` interface. You can use this interface for span
creation and customization, including setting timestamps.

SystemResource.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/system/src/main/java/io/openliberty/guides/system/SystemResource.java[]
----

InventoryResource.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[]
----

// =================================================================================================
// Testing the services
// =================================================================================================

== Testing the services

No automated tests are provided to verify the correctness of the traces. Manually verify these traces
by viewing them on the Jaeger server.

A few tests are included for you to test the basic functionality of the services. If a test failure
occurs, then you might have introduced a bug into the code.

[role='command']
include::{common-includes}/devmode-test.adoc[]

=== Running the tests

Since you started Open Liberty in dev mode, press the `enter/return` key in the shell sessions where you started the
`system` and `inventory` services to run the tests for the `system` service and the `inventory` service, respectively.

When you are done checking out the service, exit development mode by pressing CTRL+C, or by typing `q` and then
pressing the `enter/return key`. in the shell sessions where you ran the `system` and `inventory` services.

To stop the Jaeger server, run

[role='command']
----
docker container stop jaeger
docker container rm jaeger
----

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You have just used MicroProfile OpenTracing in Open Liberty to customize how and which traces are delivered to Jaeger.

Feel free to try one of the related MicroProfile guides. They demonstrate additional technologies that you
can learn to expand on top of what you built here.
[role="command"]
include::{common-includes}/attribution.adoc[subs="attributes"]
