// Copyright (c) 2017, 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-opentracing
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-guide-category: microprofile
:page-essential: false
:page-releasedate: 2018-03-16
:page-description: Explore how to enable and customize tracing of JAX-RS and non-JAX-RS methods by using Zipkin and MicroProfile OpenTracing.
:page-tags: ['MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['cdi-intro', 'microprofile-opentracing-jaeger']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:page-seo-title: Enabling distributed tracing in Java microservices using Eclipse MicroProfile OpenTracing and the Zipkin tracing system.
:page-seo-description: A getting started tutorial and an example on how to enable distributed tracing in Java microservices to easily trace request flows that span multiple resources by using MicroProfile OpenTracing and Zipkin tracing system.
:source-highlighter: prettify
:guide-author: Open Liberty
= Enabling distributed tracing in microservices with Zipkin

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to enable and customize tracing of JAX-RS and non-JAX-RS methods by using MicroProfile OpenTracing and the Zipkin tracing system.


:inv-url: http://localhost:9081/inventory/systems
:inv-url-docker: http://localhost:9080/inventory/systems
:sys-url: http://localhost:9080/system/properties
:zipkin-url: http://localhost:9411


== What you'll learn

You will learn how to enable automatic tracing for JAX-RS methods as well as create custom tracers
for non-JAX-RS methods by using MicroProfile OpenTracing.

OpenTracing is a standard API for instrumenting microservices for distributed tracing. Distributed
tracing helps troubleshoot microservices by examining and logging requests as they propagate through a
distributed system, allowing developers to tackle the otherwise difficult task of debugging these requests.
Without a distributed tracing system in place, analyzing the workflows of operations becomes difficult,
particularly in regard to pinpointing when and by whom a request is received, as well as when a response
is sent back.

MicroProfile OpenTracing enables distributed tracing in microservices without adding any explicit
distributed tracing code to the application. Note that the MicroProfile OpenTracing specification does
not address the problem of defining, implementing, or configuring the underlying distributed tracing
system. Rather, the specification makes it easy to instrument services with distributed tracing given
an existing distributed tracing system.

You will configure the provided `inventory` and `system` services to use distributed tracing with
MicroProfile OpenTracing. You will run these services in two separate JVMs made of two server instances
to demonstrate tracing in a distributed environment. If all the components were to run on a single
server, then any logging software would do the trick.


// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

For this guide, Zipkin is used as the distributed tracing system. 
You can find the installation instructions for Zipkin at the Zipkin https://zipkin.io/pages/quickstart.html[quickstart page^]. 
You are not required to use Zipkin, you may choose to use another tracing system.
However, this guide is written using Zipkin through Docker.
You will need to use different commands if you use a different tracing system.

// static guide instructions:
ifndef::cloud-hosted[]
Start Zipkin by running the following command:
[role='command']
```
docker run -d --name zipkin -p 9411:9411 openzipkin/zipkin
```

Before you proceed, make sure that your Zipkin server is up and running. By default, Zipkin can be found
at the {zipkin-url}[{zipkin-url}^] URL.
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
Start Zipkin by running the following command:
```
docker run -d --name zipkin -p 9411:9411 openzipkin/zipkin
```
{: codeblock}

Before you proceed, make sure that your Zipkin server is up and running.
Select **Launch Application** from the menu of the IDE and 
type **9411** to specify the port number for the Zipkin service. Click the **OK** button. 
Zipkin can also be found at the **`https://accountname-9411.theiadocker-4.proxy.cognitiveclass.ai`** URL, 
where **accountname** is your account name.
endif::[]

=== Try what you'll build

The `finish` directory in the root directory of this guide contains two services that are configured
to use MicroProfile OpenTracing. Give them a try before you proceed.

To try out the services, navigate to the `finish` directory and run the Maven `install` phase to build the services
[role='command']
```
cd finish
mvn install
```

then, run the Maven `liberty:start-server` goal to start them in two Open Liberty servers:
[role='command']
```
mvn liberty:start-server
```

// static guide instructions:
ifndef::cloud-hosted[]
Make sure that your Zipkin server is running and point your browser to the {inv-url}/localhost[{inv-url}/localhost^] URL. 
When you visit this URL, you make two HTTP GET requests, one to the `system` service and one to the `inventory`
service. Both of these requests are configured to be traced, so a new trace will be recorded in Zipkin.
Visit the {zipkin-url}[{zipkin-url}^] URL or another location where you configured Zipkin to run. 
Run an empty query and sort the traces by latest start time first. 
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
Make sure that your Zipkin server is running and run the following curl command:
```
curl http://localhost:9081/inventory/systems/localhost
```
{: codeblock}

When you make this curl request, you make two HTTP GET requests, one to the **system** service and 
one to the **inventory** service. 
Because tracing is configured for both these requests, a new trace is recorded in Zipkin.
Visit the **`https://accountname-9411.theiadocker-4.proxy.cognitiveclass.ai`** URL.
Run an empty query and sort the traces by latest start time first. 
endif::[]

Verify that this new trace contains three spans with the following names:

* `get:io.openliberty.guides.inventory.inventoryresource.getpropertiesforhost`
* `get:io.openliberty.guides.system.systemresource.getproperties`
* `add() span`

You can inspect each span by clicking it to reveal more detailed information, such as the time
at which the request was received and the time at which a response was sent back.

If you examine the other traces, you might notice a red trace entry, 
which indicates that the span catches an error. 
In this case, one of the tests accesses the `/inventory/systems/badhostname`
endpoint, which is invalid, so an error is thrown. This behavior is expected.

When you are done checking out the services, stop both Open Liberty servers using the Maven
`liberty:stop-server` goal:

[role='command']
```
mvn liberty:stop-server
```

// =================================================================================================
// Running the services
// =================================================================================================

== Running the services

Navigate to the `start` directory to begin.

You'll need to start the services to see basic traces appear in Zipkin. 
So, before you proceed, build and start the provided `system` and `inventory`
services in the starting project by running the Maven `install` goal:

[role='command']
```
mvn install
```

then, run the `liberty:start-server` goal:
[role='command']
```
mvn liberty:start-server
```

// static guide instructions:
ifndef::cloud-hosted[]
When the servers start, you can find the `system` and `inventory` services at the following URLs:

* {sys-url}[{sys-url}^]
* {inv-url}[{inv-url}^]
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
When the servers start, you can access the **system** service by running the following curl command:
```
curl http://localhost:9080/system/properties
```
{: codeblock}

and access the **inventory** service by running the following curl command:
```
curl http://localhost:9081/inventory/systems
```
{: codeblock}
endif::[]

// =================================================================================================
// Existing Tracer implementation
// =================================================================================================

== Existing Tracer implementation

To collect traces across your systems, you need to implement the OpenTracing `Tracer`
interface. For this guide, you can access a bare-bones `Tracer` implementation for
the Zipkin server in the form of a user feature for Open Liberty.

This feature is already configured for you in your [hotspot file=1]`pom.xml` and [hotspot file=0]`server.xml` files. 
It is automatically downloaded and installed into each service when you run a Maven build. 
You can find the [hotspot=zipkinUsr file=0]`opentracingZipkin` feature enabled in your [hotspot file=0]`server.xml` file.

The [hotspot=download file=1]`download-maven-plugin` Maven plug-in in your `pom.xml` is responsible for downloading and installing the feature.

If you want to install this feature yourself, see
https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_dist_tracing.html[Enabling distributed tracing^]
in the IBM Knowledge Centre.

server.xml
[source, xml, linenums, role='code_column']
----
include::finish/inventory/src/main/liberty/config/server.xml[]
----

pom.xml
[source, xml, linenums, role='code_column']
----
include::finish/inventory/pom.xml[]
----

// =================================================================================================
// Enabling distributed tracing
// =================================================================================================

== Enabling distributed tracing

The MicroProfile OpenTracing feature enables tracing of all JAX-RS methods by default.
To further control and customize these traces, use the `@Traced` annotation to enable and disable
tracing of particular methods. You can also inject a custom `Tracer` object to create and customize spans.

=== Enabling distributed tracing without code instrumentation

Because tracing is enabled by default for all JAX-RS methods, you need to enable only the
[hotspot=mpOpenTracing file=0]`MicroProfile OpenTracing` feature and the [hotspot=zipkinUsr file=0]`Zipkin` 
user feature in the `server.xml` file to see some basic traces in Zipkin.

Both of these features are already enabled in the `inventory` and `system` configuration files.

Make sure that your services are running. Then, simply point your browser to any of their endpoints and
check your Zipkin server for traces.

server.xml
[source, xml, linenums, role='code_column']
----
include::finish/inventory/src/main/liberty/config/server.xml[]
----

=== Enabling explicit distributed tracing

[role="code_command hotspot file=0", subs="quotes"]
----
#Update the `InventoryManager` class.#
`inventory/src/main/java/io/openliberty/guides/inventory/InventoryManager.java`
----
[role="edit_command_text"]
Enable tracing of the [hotspot=list file=0]`list()` non-JAX-RS method by updating [hotspot=Traced file=0]`@Traced` as shown.

The [hotspot=Traced file=0]`@Traced` annotation defines explicit span creation for specific classes and methods.
If you place the annotation on a class, then it's automatically applied to all methods within that class.
If you place the annotation on a method, then it overrides the class annotation if one exists.

The [hotspot=Traced file=0]`@Traced` annotation can be configured with the following two parameters:

* The `value=[true|false]` parameter indicates whether or not a particular class or method is
traced. For example, while all JAX-RS methods are traced by default, you can disable their tracing by
using the `@Traced(false)` annotation. This parameter is set to `true` by default.
* The `operationName=<Span name>` parameter indicates the name of the span that is assigned to the
particular method that is traced. If you omit this parameter, the span will be named with the following
form: `<package name>.<class name>.<method name>`. If you use this parameter at a class level, then
all methods within that class will have the same span name unless they are explicitly overridden by
another `@Traced` annotation.

The MicroProfile OpenTracing specification also makes the underlying OpenTracing `Tracer` instance available.
The configured `Tracer` is accessed by injecting it into a bean by using the 
[hotspot=customTracer file=0]`@Inject` annotation from the Contexts and Dependency Injections API.

The injected `Tracer` is used to define a custom span with the [hotspot=addSpan file=0]`add()` call. 
Then a [hotspot=childScope file=0]`childScope` is created.

InventoryManager.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[]
----

[role="code_command hotspot file=1", subs="quotes"]
----
#Update the `InventoryResource` class#
`inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java`
----
[role="edit_command_text"]
Disable tracing of the [hotspot=listContents file=1]`listContents()` JAX-RS method by setting [hotspot=Traced-false file=1]`@Traced(false)`.

InventoryResource.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[]
----

=== Injecting a custom Tracer object

The MicroProfile OpenTracing specification also makes the underlying OpenTracing `Tracer` instance
available. You can access the configured `Tracer` by injecting it into a bean by using the 
[hotspot=customTracer file=0]`@Inject` annotation from the Contexts and Dependency Injections API.

Inject the `Tracer` object into the `inventory/src/main/java/io/openliberty/guides/inventory/InventoryManager.java` file.
Then, use it to define a new child scope in the [hotspot=addSpan file=0]`add()` call.

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `InventoryManager` class.#
`inventory/src/main/java/io/openliberty/guides/inventory/InventoryManager.java`
----

InventoryManager.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[]
----

The [hotspot=Try file=0]`try` block that you see here is called a `try-with-resources` statement, 
meaning that the `childScope` object is closed at the end of the statement. 
Defining custom spans inside such statements is a good practice.
Otherwise, any exceptions that are thrown before the span is closed will leak the active span.

Next, run the following command from the `start` directory to recompile your services. 
[role="command"]
```
mvn compile
```

// static guide instructions:
ifndef::cloud-hosted[]
Visit the {inv-url}/localhost[{inv-url}/localhost^] URL, check your Zipkin server, and sort the traces by newest first. 
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
Run the following curl command, check your Zipkin server, and sort the traces by newest first:
```
curl http://localhost:9081/inventory/systems/localhost
```
{: codeblock}
endif::[]

Look for two new trace records, one for the `system` service and one for the `inventory` service. The `system` trace 
contains one span for the [hotspot=Properties file=1]`getProperties()` method in the `SystemResource` class. 
The `inventory` trace contains two spans. 
The first span is for the [hotspot=getPropertiesForHost file=2]`getPropertiesForHost()` method in the 
`InventoryResource` class. The second span is the custom span that you created around the [hotspot=Add file=0]`add()` call. 
Verify that all of these spans have the following names:

The `system` trace:

* `get:io.openliberty.guides.system.systemresource.getproperties`

The `inventory` trace:

* `get:io.openliberty.guides.inventory.inventoryresource.getpropertiesforhost`
* `add() span`

This simple example shows what you can do with the injected `Tracer` object. More configuration
options are available, including setting a timestamp for when a span was created and destroyed.
However, these options require an implementation of their own, which does not come as a part of the Zipkin
user feature that is provided. In a real-world scenario, implement all the OpenTracing interfaces that
you deem necessary, which might include the `SpanBuilder` interface. You can use this interface for span
creation and customization, including setting timestamps.

SystemResource.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/system/src/main/java/io/openliberty/guides/system/SystemResource.java[]
----

InventoryResource.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[]
----

// =================================================================================================
// Testing the services
// =================================================================================================

== Testing the services

No automated tests are provided to verify the correctness of the traces. Manually verify these traces
by viewing them on the Zipkin server.

A few tests are included for you to test the basic functionality of the services. If a test failure
occurs, then you might have introduced a bug into the code. These tests will run automatically as a
part of the Maven build process when you run the `mvn install` command. You can also run these tests
separately from the build by using the `mvn verify` command, but first make sure that the servers are
stopped.

When you are done checking out the services, stop the server by using the Maven
`liberty:stop-server` goal:

[role='command']
```
mvn liberty:stop-server
```

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
Stop the Zipkin service by running the following command:
```
docker stop zipkin
```
{: codeblock}

endif::[]

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You have just used MicroProfile OpenTracing in Open Liberty to customize how and which traces are delivered to Zipkin.

Feel free to try one of the related MicroProfile guides. They demonstrate additional technologies that you
can learn to expand on top of what you built here.
[role="command"]
include::{common-includes}/attribution.adoc[subs="attributes"]
