// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: mp-opentracing
:page-layout: guide
:page-duration: 15 minutes
// :page-releasedate: 2017-12-11
:page-description: Learn how to enable and use the OpenTracing feature in MicroProfile
:page-tags: ['MicroProfile', 'OpenTracing']
:page-permalink: /guides/{projectid}
:page-related-guides: []
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:figure-caption!:
= MicroProfile OpenTracing

Learn how to enable and use the OpenTracing feature in MicroProfile

== What you'll learn

Nothing but everything


// === What is OpenTracing?

=== Quick setup

Navigate to the `finish` directory and run `mvn package` from `inventory` and `system` directories
respectively. Navigate back to the `finish` directory and run `docker-compose up -d`. Your `inventory`
service is now running at http://localhost:9080/inventory/hosts and the Zipkin server is at http://localhost:9411/zipkin.
You can point to http://localhost:9080/inventory/hosts/sys to access the system properties of the container
running the `system` service.

To teardown all your containers run `docker-compose down`

== Start your services

=== Maven

=== Docker



// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

Next, follow https://zipkin.io/pages/quickstart.html[these] quickstart instructions for setting up
and running Zipkin. Zipkin is a distributed tracing system that is helpful when troubleshooting
problems in microservice architectures. You are not restricted to using Zipkin, but keep in mind that
this guide was written from the Zipkin perspective and you may need additional instructions that are
not lsited here if you choose to use another tracing system.

Make sure your Zipkin server is up and running before you proceed. For us, Zipkin can be accessed at http://localhost:9441

// === Try what you'll build
//
// Point to  http://localhost:9080/inventory/hosts and then to http://localhost:9080/inventory/hosts/sys,
// then back to  http://localhost:9080/inventory/hosts, then to http://localhost:9411/zipkin/ and huzzah!
//
//
// == Main section


// =================================================================================================
// Building the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

You can find the `inventory` and `system` services at:

- http://localhost:9081/inventory/systems
- http://localhost:9080/system/properties

include::{common-includes}/mvnpackage.adoc[]

=== Running with Docker

This step is entirely up to you. If you are using Docker to run your Zipkin server and you would prefer
running your services with Docker as well, then ignore the steps above and follow these instructions instead:

A `Dockerfile` and a `docker-compose.yaml` are provided under the `Docker` directory in the root directory
of this guide. Navigate to this directory and run `mvn package` to build your services. Next, make sure
your Zipkin container is stopped and run `docker-compose up -d`. This will create and start three containers:
one for the `system` service, one for the `inventory` service, and one for the Zipkin server. Once the
containers are running, the `inventory` service can then be reached at http://localhost:9080/inventory/systems
and the Zipkin server at http://localhost:9441. To retrieve the JVM system properties of the container
running the `system` service, point to http://localhost:9080/inventory/systems/sys (your `system` and `inventory`
  services are linked and therefore can access each other by their container names).


// =================================================================================================
// Testing
// =================================================================================================

// == Testing the inventory application
//
// no tests necessary?
//
//
// == Great work! You're done!
//
// yay
//
//
// Feel free to try one of the related MP guides. They demonstrate new technologies that you can learn and
// expand on top what you built in this guide.
//
// include::{common-includes}/finish.adoc[]
